#!/usr/bin/env pwsh
# Cambric App Template — Code Generators
# Usage:
#   .\scripts\cambric-generate.ps1 screen MyFeature
#   .\scripts\cambric-generate.ps1 migration

param(
    [Parameter(Position=0)][string]$Command = "",
    [Parameter(Position=1)][string]$Name    = ""
)

$ErrorActionPreference = "Stop"
$root    = Get-Location
$libPath = Join-Path $root "app\lib"

function To-Snake([string]$s) {
    return ($s -creplace '([A-Z])', '_$1').ToLower().TrimStart('_')
}

switch ($Command.ToLower()) {

    # ── screen ────────────────────────────────────────────────────────────────
    "screen" {
        if ([string]::IsNullOrWhiteSpace($Name)) {
            $Name = Read-Host "Screen name (PascalCase, e.g. MyFeature)"
        }
        if ([string]::IsNullOrWhiteSpace($Name)) { Write-Host "Name required."; exit 1 }

        # Ensure PascalCase ends with Screen removed for class name base
        $pascal  = $Name -replace 'Screen$', ''
        $snake   = To-Snake $pascal
        $dirPath  = Join-Path $libPath "screens\$snake"
        $filePath = Join-Path $dirPath "${snake}_screen.dart"

        if (Test-Path $filePath) {
            Write-Host "Already exists: $filePath" -ForegroundColor Yellow; exit 1
        }
        New-Item -ItemType Directory -Force -Path $dirPath | Out-Null

@"
import 'package:flutter/material.dart';

/// ${pascal}Screen — generated by Cambric.
///
/// Add to your navigator:
///   MaterialPageRoute(builder: (_) => const ${pascal}Screen())
class ${pascal}Screen extends StatefulWidget {
  const ${pascal}Screen({super.key});

  @override
  State<${pascal}Screen> createState() => _${pascal}ScreenState();
}

class _${pascal}ScreenState extends State<${pascal}Screen> {
  bool   _loading = false;
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() { _loading = true; _error = null; });
    try {
      // TODO: load data for this screen
      await Future.delayed(Duration.zero);
    } catch (e) {
      setState(() { _error = e.toString(); });
    } finally {
      setState(() { _loading = false; });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('$pascal')),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    if (_loading) return const Center(child: CircularProgressIndicator());
    if (_error != null) {
      return Center(child: Column(mainAxisSize: MainAxisSize.min, children: [
        Text('Error: `$_error`', style: const TextStyle(color: Colors.red)),
        const SizedBox(height: 16),
        ElevatedButton(onPressed: _load, child: const Text('Retry')),
      ]));
    }
    return const Center(child: Text('TODO: implement ${pascal}Screen'));
  }
}
"@ | Set-Content $filePath -Encoding UTF8

        Write-Host "  OK  $filePath" -ForegroundColor Green
        Write-Host ""
        Write-Host "Import:" -ForegroundColor Cyan
        Write-Host "  import 'screens/$snake/${snake}_screen.dart';"
        Write-Host ""
    }

    # ── migration ─────────────────────────────────────────────────────────────
    "migration" {
        $migPath = Join-Path $libPath "core\storage\migration_service.dart"
        if (-not (Test-Path $migPath)) {
            Write-Host "migration_service.dart not found." -ForegroundColor Red; exit 1
        }

        $content = Get-Content $migPath -Raw
        $versions = [regex]::Matches($content, 'fromVersion\s*[=:]\s*(\d+)') |
            ForEach-Object { [int]$_.Groups[1].Value }
        $cur  = if ($versions.Count -gt 0) { ($versions | Measure-Object -Maximum).Maximum } else { 0 }
        $next = $cur + 1

        Write-Host ""
        Write-Host "Current schema version: $cur" -ForegroundColor Cyan
        Write-Host "New migration: v$cur → v$next" -ForegroundColor Cyan
        Write-Host ""
        $desc = Read-Host "What changed in v${next}? (e.g. 'renamed userId to accountId')"

        $stub = @"

    // v$cur → v$next : $desc
    _MigrationStep(
      fromVersion: $cur,
      toVersion:   $next,
      description: '$desc',
      migrate: (data) {
        // TODO: transform data from v$cur to v$next
        // data['newField'] = data.remove('oldField');
        return data;
      },
    ),
"@

        if ($content -match '(?s)(final\s+List<_MigrationStep>\s+_steps\s*=\s*\[)(.*?)(\];)') {
            $replaced = $content -replace '(?s)(final\s+List<_MigrationStep>\s+_steps\s*=\s*\[)(.*?)(\];)',
                "`$1`$2$stub`n  `$3"
            $replaced | Set-Content $migPath -Encoding UTF8
            Write-Host "  OK  Migration stub added to migration_service.dart" -ForegroundColor Green
        } else {
            Write-Host "  Could not auto-insert. Add this stub to _steps manually:" -ForegroundColor Yellow
            Write-Host $stub
        }

        Write-Host ""
        Write-Host "Next steps:" -ForegroundColor Cyan
        Write-Host "  1. Implement the TODO in the migrate: function"
        Write-Host "  2. Bump schemaVersion in local_storage.dart to $next"
        Write-Host "  3. Add a migration test in test/core/migration_service_test.dart"
        Write-Host ""
    }

    default {
        Write-Host ""
        Write-Host "Cambric Code Generator" -ForegroundColor Cyan
        Write-Host "  .\scripts\cambric-generate.ps1 screen <Name>   Create a screen scaffold"
        Write-Host "  .\scripts\cambric-generate.ps1 migration        Generate a migration stub"
        Write-Host ""
    }
}
